### ISSUE TITLE
Just a thanks

### ISSUE THREAD

**Issue by rogerleite** [ksylvan/docker-pgmodeler#1]
Hi @ksylvan 

Thanks for this repo. Helped me a lot.

Cheers,
Roger

**Comment by ksylvan** [comment]
You are welcome!

**Comment by ksylvan** [comment]
Your note prompted me to update to the latest version. `docker pull` to see version `0.9.1-beta1`

**Comment by rogerleite** [comment]
@ksylvan Thanks again! 👍 👏
