### ISSUE TITLE
Please update to 0.9.1 stable

### ISSUE THREAD

**Issue by jadbox** [ksylvan/docker-pgmodeler#3]
Currently on 0.9.1 beta1

**Comment by ksylvan** [comment]
Just merged this https://github.com/ksylvan/docker-pgmodeler/pull/2 which should handle this request. Thank you!

**Comment by ksylvan** [comment]
https://hub.docker.com/r/kayvan/pgmodeler/builds/ shows the latest and 0.9.1 tag are built.
